### ISSUE TITLE
How to process remote notification when App is inactive or background?

### ISSUE THREAD

**Issue by jerry-sl** [mpurbo/MMPReactiveNotification#1]
When i tap notification center to open my app,how to use MMPReactiveNotification process UIApplicationLaunchOptionsRemoteNotificationKey. I noticed there is a localNotificationOnLaunch method,  is it possible to have a remoteNotificationsOnLaunch?

**Comment by mpurbo** [comment]
Hi,

Yes it's possible but it will have to share the underlying multicasted signal. The underlying is not currently a multicast and it's a signal generated from protocol (https://github.com/mpurbo/MMPReactiveNotification/blob/master/Classes/MMPReactiveNotification.m#L171).

Anyway, I'll add that method but I don't currently have time to test it so I will just release it without test. It'll be great if you could help me out trying it out and report an issue if you have problem.

**Comment by mpurbo** [comment]
On second thought, it doesn't really have to be multicasted since rac_signalForSelector:fromProtocol: is just returning the same signal however many times we call it.

**Comment by mpurbo** [comment]
I just released 0.3.2. Let me know if there's a problem
