### ISSUE TITLE
Remove scheduled local notifications

### ISSUE THREAD

**Issue by robertodias180** [mpurbo/MMPReactiveNotification#2]
Is there a way to remove scheduled notifications?

thanks

**Comment by mpurbo** [comment]
Currently I don't have plan to include it in this library because it's simple enough to use plain UIApplication to cancel a notification (see: https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/#//apple_ref/occ/instm/UIApplication/cancelLocalNotification:).
